name: Wasm Pack
on:
  push:
    branches:
      - release
jobs:
  build-publish:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    name: Build and publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: Wasm Pack
        uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build wasm -t web -d ../svelte/src/wasm/
      - name: Build Svelte
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a5072175ae8b2ac798c0583ac6da2f0d
          projectName: dorb
          directory: .svelte-kit/cloudflare
          workingDirectory: svelte
          wranglerVersion: '3'
