name: Wasm Pack
on:
  push:
    branches:
      - release
jobs:
  wasm-pack:
    runs-on: ubuntu-latest
    steps:
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0
      - run: wasm-pack build ../wasm -t web -d src/wasm/
            